USE ContosoRetailDW

SELECT GETDATE() AS DATA_ATUAL

SELECT GETDATE()+10 AS DATA_ATUAL10

SELECT YEAR(GETDATE()) AS ANO

SELECT
	*
FROM FactOnlineSales
WHERE YEAR(DateKey) = 2007 AND
MONTH(DATEKEY) = 12 AND
DAY(DATEKEY) = 31