USE ContosoRetailDW

SELECT TOP 100
	S.DateKey,
	DATEPART(YEAR, S.DateKey) AS ANO,
	DATEPART(MONTH, S.DateKey) AS MES,
	DATEPART(DAY, S.DateKey) AS DIA,
	DATEPART(DAYOFYEAR, S.DateKey) AS DIADOANO
FROM FactOnlineSales S
ORDER BY S.DateKey DESC

SELECT DATEPART(WEEKDAY, GETDATE()+3) AS DIADASEMANAa