USE ContosoRetailDW;

WITH TOTAL_VENDAS(ANO, MES, VENDAS) AS
(
	SELECT
		DATEPART(YEAR, S.Datekey) AS ANO,
		DATEPART(MONTH, S.Datekey) AS MES,
		SUM(S.SalesAmount) AS VENDAS
	FROM FactOnlineSales S
	GROUP BY DATEPART(YEAR, S.Datekey), DATEPART(MONTH, S.Datekey)
)
SELECT
	ANO, MES, 
	FORMAT(VENDAS, 'C0') AS 'VENDAS',
	FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO ORDER BY MES), 'C0') AS VENDAS_YTD,
	FORMAT(SUM(VENDAS) OVER(PARTITION BY ANO), 'C0') AS VENDAS_TOTAL_ANO	
FROM TOTAL_VENDAS
ORDER BY ANO, MES