USE ContosoRetailDW;

WITH TOTAL_VENDAS(ANO, MES, VENDAS) AS
(
	SELECT
		DATEPART(YEAR, S.Datekey) AS ANO,
		DATEPART(MONTH, S.Datekey) AS MES,
		SUM(S.SalesAmount) AS VENDAS
	FROM FactOnlineSales S
	GROUP BY DATEPART(YEAR, S.Datekey), DATEPART(MONTH, S.Datekey)
)
SELECT
	ANO, MES, 
	FORMAT(VENDAS, 'C0') AS 'VENDAS',
	FORMAT(LAG(VENDAS,1,0) OVER (ORDER BY ANO, MES ASC), 'C0') AS MES_ANTERIOR,
	FORMAT(LEAD(VENDAS,1,0) OVER (ORDER BY ANO, MES ASC), 'C0') AS MES_POSTERIOR
FROM TOTAL_VENDAS
ORDER BY ANO, MES